#live server configurations
##########################
#   RTMP configurations  #
##########################
[rtmp]
enabled = true
port = 1935

##########################
#   LOG configurations   #
##########################
[log]
level = "info"
#level = "trace"
