#live server configurations
#######################################
#   RTMP configurations(stand-alone)  #
#######################################
[rtmp]
enabled = true
port = 1935


######################################
#    HLS configurations              #
######################################
[hls]
enabled = true
port = 8080

########################################
# HTTPFLV configurations               #
########################################
[httpflv]
enabled = true
port = 8081

#######################################
#   LOG configurations                #
#######################################
[log]
level = "info"