# syntax=docker/dockerfile:1
# escape=`

# XIU stream/restream server
# Test image

# Glob build args, config, and user management 
# ARG PLATFORM=${PLATFORM}
# ARG VERSION=${VERSION}

# ---

# 1. Base image
FROM --platform=${PLATFORM} alpine:${VERSION} AS base

# Base setup
RUN apk cache sync `
    && apk --update-cache upgrade --no-cache `
    && apk add "alpine-conf" `
    && setup-timezone -i ${TZ} `
    && apk del "alpine-conf" `
    && rm -rf "/var/cache/apk" "/etc/apk/cache" `
    && adduser `
    --uid "10001" `
    --gecos "Special no-login user for app." `
    --shell "/sbin/nologin" `
    --home "/nonexistent" `
    --no-create-home `
    --disabled-password `
    ${USER};

# ---

# 2. Build app
FROM base AS builder

# Builder args, TZ and CWD
# ARG BUILDER_TIMEZONE="Europe/Brussels"
# ARG APP_VERSION="v0.6.1"
ENV PATH="/root/.cargo/bin:${PATH}"
ENV TZ=${BUILDER_TZ}
WORKDIR "/build"

# Get toolchain
RUN apk cache sync `
    && apk --update-cache upgrade --no-cache `
    && apk add --no-cache `
        "openssl-dev" "pkgconf" "git" "rustup" `
        "musl-dev" "gcc" `
    && rm -rf "/var/cache/apk" "/etc/apk/cache";
RUN rustup-init -q -y `
                --component "cargo" "x86_64-unknown-linux-musl" `
                --default-host "x86_64-unknown-linux-musl";

# RUN setup-timezone -i ${BUILDER_TZ}

# Copying source and building
RUN git clone "https://github.com/harlanc/xiu.git" --branch "master" `
    && cd "xiu" `
    && git checkout -b "publish" "tags/"${APP_VERSION};
RUN cargo build --manifest-path "xiu/application/xiu/Cargo.toml" `
                --target "x86_64-unknown-linux-musl" `
                --release;

# ---

# 3. Run app
FROM base AS runner

# Runner args and CWD
# ARG TIMEZONE
# ARG USER="appuser"
WORKDIR ${APP_PATH}

# Install deps and create app user
# RUN --mount=type="cache",from="builder",src="/sys_setup/alpine_setup_answers.conf",dst="/sys_setup/" `
# apk add --no-cache "libgcc" `


# Copy app
COPY --from=builder "/build/xiu/target/release/xiu/." "."

# Runner env
# ENV TZ=${TIMEZONE}
# ENV SYSROOT="/dummy"
# ENV PATH=${PATH}:${APP_PATH}

# Switch user
USER ${USER}

# Ports
EXPOSE "80"
EXPOSE "80/udp"
EXPOSE "443"
EXPOSE "1935"
EXPOSE "1935/udp"
EXPOSE "8000"
EXPOSE "8000/udp"

# Start app in exec mode
ENTRYPOINT [ "xiu" ]
